(function(){
"use strict";
var C,overlay,video,stage,aspectMenu,current=null,saveTimer=null,hideTimer=null,opened=false,aspect="auto";
function init(){C=AuroraCore;overlay=C.byId("playerOverlay");video=C.byId("video");stage=C.byId("videoStage");aspectMenu=C.byId("aspectMenu");C.byId("playerBack").onclick=close;C.byId("playPauseBtn").onclick=toggle;C.byId("rewindBtn").onclick=function(){seek(-10)};C.byId("forwardBtn").onclick=function(){seek(10)};C.byId("restartBtn").onclick=restart;C.byId("aspectBtn").onclick=toggleAspectMenu;Array.prototype.forEach.call(aspectMenu.querySelectorAll("[data-aspect]"),function(b){b.onclick=function(){setAspect(b.getAttribute("data-aspect"));aspectMenu.classList.add("hidden");showControls()}});video.addEventListener("timeupdate",update);video.addEventListener("play",updatePlayIcon);video.addEventListener("pause",updatePlayIcon);video.addEventListener("ended",function(){persist();showControls()});video.addEventListener("error",onError);document.addEventListener("mousemove",function(){if(opened)showControls()});setAspect(C.read("aspect","auto"))}
function isOpen(){return opened} function play(item,url){if(!url){C.toast("Não foi possível montar o endereço deste conteúdo.");return}current=item;opened=true;overlay.classList.remove("hidden");overlay.classList.remove("controls-hidden");aspectMenu.classList.add("hidden");C.byId("playerTitle").textContent=item.title||"Reprodução";C.byId("playerKind").textContent=item.type==="live"?"CANAL AO VIVO":item.type==="episode"?"EPISÓDIO":"FILME";C.byId("liveBadge").classList.toggle("hidden",item.type!=="live");C.byId("timeline").classList.toggle("hidden",item.type==="live");C.byId("currentTime").classList.toggle("hidden",item.type==="live");C.byId("durationTime").classList.toggle("hidden",item.type==="live");video.src=url;video.load();var p=C.getProgress(item);video.onloadedmetadata=function(){if(item.type!=="live"&&p&&p.position>8&&p.percent<.97){try{video.currentTime=Math.min(p.position,Math.max(0,video.duration-3));C.toast("Continuando de "+C.fmt(p.position))}catch(e){}}var pr=video.play();if(pr&&pr.catch)pr.catch(function(){showControls()})};clearInterval(saveTimer);saveTimer=setInterval(persist,5000);showControls();setTimeout(function(){C.byId("playPauseBtn").focus()},80)}
function close(){if(!opened)return true;if(!aspectMenu.classList.contains("hidden")){aspectMenu.classList.add("hidden");C.byId("aspectBtn").focus();return true}persist();opened=false;clearInterval(saveTimer);clearTimeout(hideTimer);try{video.pause();video.removeAttribute("src");video.load()}catch(e){}overlay.classList.add("hidden");if(window.AuroraApp&&AuroraApp.restoreFocus)AuroraApp.restoreFocus();return true}
function persist(){if(!current||current.type==="live"||!video)return;C.saveProgress(current,video.currentTime||0,isFinite(video.duration)?video.duration:0)} function toggle(){if(video.paused){var p=video.play();if(p&&p.catch)p.catch(function(){})}else video.pause();showControls()} function restart(){if(current&&current.type!=="live"){try{video.currentTime=0;video.play()}catch(e){}showControls()}} function seek(n){if(!current||current.type==="live")return;try{video.currentTime=Math.max(0,Math.min(video.duration||1e9,video.currentTime+n))}catch(e){}showControls()}
function update(){if(!video||current&&current.type==="live")return;var d=isFinite(video.duration)?video.duration:0,p=d?Math.max(0,Math.min(100,(video.currentTime/d)*100)):0;C.byId("progressBar").style.width=p+"%";C.byId("currentTime").textContent=C.fmt(video.currentTime);C.byId("durationTime").textContent=C.fmt(d)} function updatePlayIcon(){if(C&&C.byId("playPauseBtn"))C.byId("playPauseBtn").textContent=video.paused?"▶":"Ⅱ"}
function showControls(){if(!opened)return;overlay.classList.remove("controls-hidden");clearTimeout(hideTimer);if(!video.paused&&aspectMenu.classList.contains("hidden"))hideTimer=setTimeout(function(){overlay.classList.add("controls-hidden")},4500)} function toggleAspectMenu(){aspectMenu.classList.toggle("hidden");showControls();if(!aspectMenu.classList.contains("hidden")){var b=aspectMenu.querySelector("[data-aspect='"+aspect+"']")||aspectMenu.querySelector("button");if(b)b.focus()}}
function setAspect(mode){if(mode==="reset")mode="auto";aspect=mode||"auto";["mode-auto","mode-original","mode-letterbox","mode-fill","mode-169","mode-43","mode-zoom"].forEach(function(c){stage.classList.remove(c)});var cls=mode==="16:9"?"mode-169":mode==="4:3"?"mode-43":"mode-"+mode;stage.classList.add(cls);C.write("aspect",mode);var labels={original:"Original",auto:"Automático",letterbox:"Letterbox",fill:"Preencher tela","16:9":"16:9","4:3":"4:3",zoom:"Zoom"};C.byId("aspectLabel").textContent=labels[mode]||"Automático"}
function onError(){if(!opened)return;var code=video.error?video.error.code:0,msg=code===4?"Formato/codec não suportado pela TV ou endereço indisponível.":"Falha ao reproduzir este conteúdo.";C.toast(msg,4200);showControls()}
function handleKey(e){if(!opened)return false;var code=e.keyCode||e.which;showControls();if(code===10009||code===8||e.key==="Escape")return close();if(code===415){video.play();return true}if(code===19){video.pause();return true}if(code===413){return close()}if(code===412){seek(-10);return true}if(code===417){seek(10);return true}if(code===10252){toggle();return true}if(code===37){C.move("left");return true}if(code===38){C.move("up");return true}if(code===39){C.move("right");return true}if(code===40){C.move("down");return true}if(code===13){var el=document.activeElement;if(el&&typeof el.click==="function")el.click();return true}return false}
window.AuroraPlayer={init:init,play:play,close:close,isOpen:isOpen,handleKey:handleKey,setAspect:setAspect};
})();