"use strict";
var fs=require("fs"),path=require("path"),root=path.resolve(__dirname,".."),required=["package.json","index.html","style.css","core.js","xtream.js","mock.js","player.js","app.js","service.js","dev-server.js"],fail=[];
required.forEach(function(f){if(!fs.existsSync(path.join(root,f)))fail.push("Arquivo ausente: "+f)});
var pkg=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8"));
if(pkg.packageType!=="app")fail.push("packageType deve ser app");
if(pkg.appPath!=="index.html")fail.push("appPath incorreto");
if(pkg.appName!=="Aurora TV")fail.push("appName incorreto");
if(pkg.serviceFile!=="service.js")fail.push("serviceFile ausente/incorreto");
var html=fs.readFileSync(path.join(root,"index.html"),"utf8"),css=fs.readFileSync(path.join(root,"style.css"),"utf8"),app=fs.readFileSync(path.join(root,"app.js"),"utf8"),player=fs.readFileSync(path.join(root,"player.js"),"utf8"),xtream=fs.readFileSync(path.join(root,"xtream.js"),"utf8"),service=fs.readFileSync(path.join(root,"service.js"),"utf8"),core=fs.readFileSync(path.join(root,"core.js"),"utf8");
["serverInput","mainNav","playerOverlay","aspectMenu","video","avPlayer"].forEach(function(x){if(html.indexOf('id="'+x+'"')<0)fail.push("Elemento ausente: "+x)});
if(html.indexOf("$WEBAPIS/webapis/webapis.js")<0)fail.push("WebAPI Samsung ausente");
["original","auto","letterbox","fill","16:9","4:3","zoom","reset"].forEach(function(m){if(html.indexOf('data-aspect="'+m+'"')<0)fail.push("Modo de imagem ausente: "+m)});
if(app.indexOf("seriesInfo")<0||app.indexOf("continueItems")<0)fail.push("Integração de séries/continuar assistindo incompleta");
if(app.indexOf("categoryCache")<0||app.indexOf("loadInitialCatalog")<0)fail.push("Cache/catálogo incremental ausente");
if(app.indexOf("raw:x")>=0)fail.push("Objetos brutos Xtream ainda estão sendo mantidos em memória");
if(player.indexOf("webapis.avplay")<0||player.indexOf("setDisplayRect")<0||player.indexOf("setBufferingParam")<0)fail.push("AVPlay nativo incompleto");
if(player.indexOf("Reconectando canal")<0||player.indexOf("formato alternativo")<0)fail.push("Fallback/reconexão do live ausente");
if(css.indexOf(".mode-43")<0||css.indexOf(".mode-zoom")<0||css.indexOf("#avPlayer")<0)fail.push("CSS do player incompleto");
if(xtream.indexOf("127.0.0.1:18081/proxy")<0)fail.push("Proxy Xtream da TV ausente");
if(xtream.indexOf("loadInitialCatalog")<0||xtream.indexOf("livePreference")<0||xtream.indexOf("return\"ts\"")<0)fail.push("Catálogo incremental/modo live automático ausente");
if(service.indexOf('server.listen(PORT,"127.0.0.1"')<0)fail.push("Serviço proxy local ausente");
if(service.indexOf('"Accept-Encoding":"gzip, deflate"')<0||service.indexOf('"Content-Encoding"')<0)fail.push("Compressão do proxy ausente");
if(core.indexOf("MutationObserver")<0||core.indexOf("favCache")<0||core.indexOf("progressCache")<0)fail.push("Otimizações de navegação/cache local ausentes");
if(fail.length){console.error("FALHOU\n- "+fail.join("\n- "));process.exit(1)}
console.log("OK - Aurora TV v"+pkg.version+" passou nos testes estruturais e de otimização.");
